nome = input('Digite seu nome: ')
altura = float(input('Digite sua altura em metros: '))
peso = float(input('Digite seu peso em kg: '))
imc = peso / (altura ** 2)
print('Nome:', nome)
print('Altura:', altura)
print('Peso:', peso)
print('IMC:', imc)